module.exports = [
  {
    makerName : "Dollar Tree",
    itemName : "Del Monte Fruit Refreshers",
    link : "none",
    discountAmount : "Free",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "free",
  },
  {
    makerName : "Walmart",
    itemName : "pizza",
    link : "none",
    discountAmount : "$1.00",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "pizza",
  },
  {
    makerName : "Clorox",
    itemName : "bleach",
    link : "none",
    discountAmount : "$5.00",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "household",
  },
  {
    makerName : "Giordanos",
    itemName : "pizza",
    link : "none",
    discountAmount : "$1.00 on TWO",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "pizza",
  },
  {
    makerName : "Pantene",
    itemName : "shampoo",
    link : "none",
    discountAmount : "$6.00",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "bath",
  },
  {
    makerName : "Red Baron",
    itemName : "pizza",
    link : "none",
    discountAmount : "$1.00",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "pizza",
  },
  {
    makerName : "McDonalds",
    itemName : "burger",
    link : "none",
    discountAmount : "BOGO",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "fast-food",
  },
  {
    makerName : "Little Cesars",
    itemName : "pizza",
    link : "none",
    discountAmount : "$1.00 on Lunch Box",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "pizza",
  },
  {
    makerName : "Rite Aid",
    itemName : "pizza",
    link : "none",
    discountAmount : "$5.00 back when you spend $25",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "pharmacy",
  },
  {
    makerName : "Sarah Lee",
    itemName : "pound cake",
    link : "none",
    discountAmount : "Free",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "free",
  },
  {
    makerName : "Talenti",
    itemName : "ice cream",
    link : "none",
    discountAmount : "$1.00 on any two",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "sweets",
  },
  {
    makerName : "MB USA",
    itemName : "SLK550",
    link : "none",
    discountAmount : "$1000 off cash back",
    expirationDate : "08/31/19",
    storeCoupon : true,
    tags : "cars",
  }
]
