module.exports = [
  {
    makerName : "Red 52342Baron",
    itemName : "pizza",
    link : "none",
    discountAmount : "$1.00",
    expirationDate : "08/31/19",
    storeCoupon : true,
    notes : "pizza",
  },
  {
    makerName : "12312Red Baron",
    itemName : "pizza",
    link : "none",
    discountAmount : "$1.00",
    expirationDate : "08/31/19",
    storeCoupon : true,
    notes : "pizza",
  },
  {
    makerName : "Red3243242 Baron",
    itemName : "pizza",
    link : "none",
    discountAmount : "$1.00",
    expirationDate : "08/31/19",
    storeCoupon : true,
    notes : "pizza",
  },
  {
    makerName : "Redfdsafdsaf Baron",
    itemName : "pizza",
    link : "none",
    discountAmount : "$1.00",
    expirationDate : "08/31/19",
    storeCoupon : true,
    notes : "pizza",
  },
  {
    makerName : "Red fdsafdsaBaron",
    itemName : "pizza",
    link : "none",
    discountAmount : "$1.00",
    expirationDate : "08/31/19",
    storeCoupon : true,
    notes : "pizza",
  },
  {
    makerName : "Red Baron",
    itemName : "pizza",
    link : "none",
    discountAmount : "$1.00",
    expirationDate : "08/31/19",
    storeCoupon : true,
    notes : "pizza",
  },
  {
    makerName : "Red Baron",
    itemName : "pizza",
    link : "none",
    discountAmount : "$1.00",
    expirationDate : "08/31/19",
    storeCoupon : true,
    notes : "pizza",
  },
  {
    makerName : "Red Baron",
    itemName : "pizza",
    link : "none",
    discountAmount : "$1.00",
    expirationDate : "08/31/19",
    storeCoupon : true,
    notes : "pizza",
  },
  {
    makerName : "2131Red Baron",
    itemName : "pizza",
    link : "none",
    discountAmount : "$1.00",
    expirationDate : "08/31/19",
    storeCoupon : true,
    notes : "pizza",
  },
  {
    makerName : "21313Red Baron",
    itemName : "pizza",
    link : "none",
    discountAmount : "$1.00",
    expirationDate : "08/31/19",
    storeCoupon : true,
    notes : "pizza",
  },
  {
    makerName : "324242Red Baron",
    itemName : "pizza",
    link : "none",
    discountAmount : "$1.00",
    expirationDate : "08/31/19",
    storeCoupon : true,
    notes : "pizza",
  },
  {
    makerName : "12312Red Baron",
    itemName : "pizza",
    link : "none",
    discountAmount : "$1.00",
    expirationDate : "08/31/19",
    storeCoupon : true,
    notes : "pizza",
  }
]
